=== JuicingJuicer/solvd-database/src/main/resources/xml/buildingTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="buildingTypes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="buildingType" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="buildingTypeId" type="xs:int"/>
              <xs:element name="buildingName" type="xs:string"/>
              <xs:element name="buildingTag" type="xs:string"/>
              <xs:element name="additionalDetails" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JuicingJuicer/solvd-database/src/main/resources/xml/buildingTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<buildingTypes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="buildingTypes.xsd">
	<buildingType>
		<buildingTypeId>1</buildingTypeId>
		<buildingName>Office</buildingName>
		<buildingTag>BUSINESS</buildingTag>
		<additionalDetails> </additionalDetails>
	</buildingType>
	<buildingType>
		<buildingTypeId>2</buildingTypeId>
		<buildingName>House</buildingName>
		<buildingTag>RESIDENTIAL</buildingTag>
		<additionalDetails>1 story</additionalDetails>
	</buildingType>
	<buildingType>
		<buildingTypeId>3</buildingTypeId>
		<buildingName>WareHouse</buildingName>
		<buildingTag>STORAGE</buildingTag>
		<additionalDetails>cold storage</additionalDetails>
	</buildingType>
</buildingTypes>
