=== JuicingJuicer/solvd-database/src/main/resources/xml/employees.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="employees">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="employee" maxOccurs="unbounded">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="empId" type="xs:int"/>
              <xs:element name="firstName" type="xs:string"/>
              <xs:element name="lastName" type="xs:string"/>
              <xs:element name="age" type="xs:int"/>
              <xs:element name="email" type="xs:string"/>
              <xs:element name="phoneNumber" type="xs:string"/>
              <xs:element name="job">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="jobId" type="xs:int"/>
                    <xs:element name="jobTitle" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="teams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="team" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="teamId" type="xs:int"/>
                          <xs:element name="teamName" type="xs:string"/>
                          <xs:element name="teamDetails" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JuicingJuicer/solvd-database/src/main/resources/xml/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employees.xsd">
	<employee>
		<empId>1</empId>
		<firstName>Gene</firstName>
		<lastName>Cousineau</lastName>
		<age>60</age>
		<email>gcousineau@gmail.com</email>
		<phoneNumber>20995175348</phoneNumber>
		<job>
			<jobId>1</jobId>
			<jobTitle>Construction Manager</jobTitle>
		</job>
		<teams>
			<team>
				<teamId>1</teamId>
				<teamName>Team A</teamName>
				<teamDetails> </teamDetails>
			</team>
			<team>
				<teamId>2</teamId>
				<teamName>Team B</teamName>
				<teamDetails>Elite</teamDetails>
			</team>
		</teams>>
	</employee>
	<employee>
		<empId>2</empId>
		<firstName>Barry</firstName>
		<lastName>Block</lastName>
		<age>40</age>
		<email>bblock@gmail.com</email>
		<phoneNumber>2099514725</phoneNumber>
		<job>
			<jobId>2</jobId>
			<jobTitle>Civil Engineer</jobTitle>
		</job>
		<teams>
			<team>
				<teamId>2</teamId>
				<teamName>Team B</teamName>
				<teamDetails>Elite</teamDetails>
			</team>
		</teams>
	</employee>
</employees>
