=== JuicingJuicer/solvd-database/src/main/resources/xml/materials.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="materials">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="material" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="materialId" type="xs:int"/>
              <xs:element name="materialName" type="xs:string"/>
              <xs:element name="materialDesc" type="xs:string"/>
              <xs:element name="materialPrice" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JuicingJuicer/solvd-database/src/main/resources/materials.xml
<?xml version="1.0" encoding="UTF-8"?>
<materials xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="materials.xsd">
	<material>
		<materialId>1</materialId>
		<materialName>Wood</materialName>
		<materialDesc>1 cord of wood</materialDesc>
		<materialPrice>500</materialPrice>
	</material>
	<material>
		<materialId>2</materialId>
		<materialName>Granite</materialName>
		<materialDesc>per cubic yard</materialDesc>
		<materialPrice>80</materialPrice>
	</material>
	<material>
		<materialId>3</materialId>
		<materialName>Glass</materialName>
		<materialDesc>per square foot</materialDesc>
		<materialPrice>25</materialPrice>
	</material>
</materials>
