=== JuicingJuicer/solvd-database/src/main/resources/xml/sites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="sites">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="site">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="siteId" type="xs:int"/>
              <xs:element name="address" type="xs:string"/>
              <xs:element name="city">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="cityId" type="xs:int"/>
                    <xs:element name="cityName" type="xs:string"/>
                    <xs:element name="state">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="stateId" type="xs:int"/>
                          <xs:element name="stateName" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="zip" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JuicingJuicer/solvd-database/src/main/resources/xml/sites.xml
<?xml version="1.0" encoding="UTF-8"?>
<sites xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="sites.xsd">
	<site>
		<siteId>1</siteId>
		<address>308 Negra Arroyo Lane</address>
		<city>
			<cityId>1</cityId>
			<cityName>Albuquerque</cityName>
			<state>
				<stateId>2</stateId>
				<stateName>New Mexico</stateName>
			</state>
		</city>
		<zip>87111</zip>
	</site>
</sites>
